# Generated by Django 5.1.5 on 2025-09-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisaTebu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('brix', models.FloatField()),
                ('pol', models.FloatField()),
                ('suhu', models.FloatField()),
            ],
        ),
    ]
