# Generated by Django 5.1.5 on 2025-09-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisa_tebu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisatebu',
            name='ph',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
